GET http://localhost:5000/warga

###
POST http://localhost:5000/send-email

###

GET http://localhost:5000/history-kebijakan/join/table/USER_2

###

GET http://localhost:5000/warga

###

POST http://localhost:5000/survey
Content-Type: application/json

{
    "id_survey": "SRVY_1",
    "user_id": "USER_1",
    "no_kk": "213123",
    "id_kriteria": "KB_1",
    "id_prioritas": "PRIO_1",
    "verifikasi_kondisi": "test",
    "keterangan": "test",
    "identitas_survey": 0
}

###

POST http://localhost:5000/pesan-balas
Content-Type: application/json

{
    "kd_pesan_balas": "PB_2",
    "user_id": "USER_11",
    "kd_masukan": "MS_4",
    "pesan_balas": "test"
}

###

DELETE http://localhost:5000/kriteria/KB_5

###
DELETE http://localhost:5000/uploads/delete/imgUser/null

###

GET http://localhost:5000/warga/userId/USER_5

###

PATCH  http://localhost:5000/warga/update/2222
Content-Type: application/json

{
    "status_rekomendasi": "tidak memenuhi"
}
###

PATCH  http://localhost:5000/users/USER_1
Content-Type: application/json

{
    "nm_depan": "eunha",
    "nm_belakang": "umji"
}

###

GET  http://localhost:5000/warga/userId/USER_2

###

GET  http://localhost:5000/bantuan/100/tersedia

###

DELETE   http://localhost:5000/uploads/delete/imgUser/IMG_20180302_121043.jpg

###