GET http://localhost:5000/warga

###

GET http://localhost:5000/nilai-prioritas/USER_6

###

POST http://localhost:5000/nilai-prioritas
Content-Type: application/json

{
    "prioritas_id": "PRIO_7",
    "user_id": "USER_11",
    "id_kriteria": "KB_3",
    "pilihan": "test lagi",
    "total_nilai": 20
}

###

PATCH http://localhost:5000/users/USER_2
Content-Type: application/json

{
    "gambar": "123.jpg"
}

###

DELETE http://localhost:5000/kriteria/KB_5

###

GET http://localhost:5000/bantuan/kapasitas/100

###

PATCH  http://localhost:5000/kriteria/KB_2
Content-Type: application/json

{
    "nilai_prioritas": 2.57
}
###

PATCH  http://localhost:5000/users/USER_1
Content-Type: application/json

{
    "nm_depan": "eunha",
    "nm_belakang": "umji"
}

###

GET  http://localhost:5000/bantuan/id/BNT_2

###

GET  http://localhost:5000/bantuan/100/tersedia

###