GET http://localhost:5000/bantuan

###

GET http://localhost:5000/acara/58

###

POST http://localhost:5000/bantuan
Content-Type: application/json

{
    "kd_bantuan": "BNT_5",
    "nama": "abdu",
    "kapasitas": "10"
}

###

PATCH http://localhost:5000/users/USER_2
Content-Type: application/json

{
    "gambar": "123.jpg"
}

###

DELETE http://localhost:5000/masukan/USER_1

###

GET http://localhost:5000/masukan

###

PATCH  http://localhost:5000/users/USER_11
Content-Type: application/json

{
    "role": "warga"
}
###

PATCH  http://localhost:5000/users/USER_1
Content-Type: application/json

{
    "nm_depan": "eunha",
    "nm_belakang": "umji"
}

###

GET  http://localhost:5000/bantuan/id/BNT_2

###

GET  http://localhost:5000/bantuan/100/tersedia

###